### PR TITLE
Migration to 16.0

### PR DESCRIPTION
**Pull request by maq-adhoc**
[MIG] l10n_ar_afipws: Migration to 16.0 https://github.com/ingadhoc/odoo-argentina-ce/commit/85248038e674abe444ffcc564bb4d558d9512a07

[MIG] l10n_ar_afipws_fe: Migration to 16.0 https://github.com/ingadhoc/odoo-argentina-ce/commit/c3e626adab10b39465f7e87c1f60be99eefeab77

[MIG] l10n_ar_reports: Migration to 16.0 https://github.com/ingadhoc/odoo-argentina-ce/commit/e0ac13094c570380b4e56108b0dbe999405c569e 

[MIG] l10n_ar_pos_afipws_fe: Migration to 16.0 https://github.com/ingadhoc/odoo-argentina-ce/commit/94e9e9cbe5249d294e0d806bd0ac1393c01ec140

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ce/pull/43).

**Comment by filoquin** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin: I must know your email before you can review PRs. Please contact an administrator.

**Review by filoquin — DISMISSED** [review]
Primera version para 16

**Comment by filoquin** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin: I must know your email before you can review PRs. Please contact an administrator.

**Comment by roboadhoc** [comment]
I didn't know about this PR and had to retrieve its information, you may have to re-approve it as I didn't see previous commands.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/43).

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin. I'm afraid I can't do that.

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin. I'm afraid I can't do that.

**Comment by maq-adhoc** [comment]
@roboadhoc override=ci/runbot-odoo-argentina-ce

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by nicomacr** [comment]
@roboadhoc r+

**Pull request closed without merging**
