### PR TITLE
[FW][WIP] Reorder CAEA

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/odoo-argentina-ce#41

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ce/pull/44).

**Comment by fw-bot-adhoc** [comment]
@filoquin @jjscarafia this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@filoquin @jjscarafia ci/argentina-ce failed on this forward-port PR

**Comment by jjscarafia** [comment]
@fw-bot-adhoc r+ override=ci/argentina-ce

**Comment by roboadhoc** [comment]
@jjscarafia you may want to rebuild or fix this PR as it has failed CI.

**Comment by jjscarafia** [comment]
cerrado, se sigue en https://github.com/ingadhoc/odoo-argentina-ce/pull/43

**Pull request closed without merging**
