### PR TITLE
[FIX] l10n_ar_afipws, l10n_ar_afipws_caea: fixes

### PR DESCRIPTION
**Pull request by ica-adhoc**
Se cambiaron algunos archivos para intentar solucionar
el error que lanza el runbot al intentar levantar build

### CODE REVIEW

**Comment by zaoral** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
Sorry, I didn't know about this PR and had to retrieve its information, you may have to re-approve it.

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ce/pull/37).

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. This PR is already reviewed, reviewing it again is useless.

**Comment by zaoral** [comment]
@roboadhoc r+ override=ci/argentina-ce

**Comment by zaoral** [comment]
@roboadhoc  override=ci/argentina-ce

**Comment by roboadhoc** [comment]
@zaoral, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status.

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/argentina-ce

**Pull request closed without merging**
