### PR TITLE
[FIX] Fix issue https://github.com/ingadhoc/odoo-argentina-ce/issues/…

### PR DESCRIPTION
**Pull request by filoquin**
…28 and  https://github.com/ingadhoc/odoo-argentina-ce/issues/32

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/47).

**Comment by filoquin** [comment]
@roboadhoc  r+

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin: you can't review+.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by nicomacr** [comment]
@roboadhoc retry

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr: retry makes no sense when the PR is not in error.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/runbot-odoo-argentina-ce

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/odoo-argentina-ce#48

**Comment by fw-bot-adhoc** [comment]
@filoquin @maq-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/odoo-argentina-ce#48

**Pull request closed without merging**
