### PR TITLE
[FIX] FIX QR code invoice URL

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/59).

**Comment by maq-adhoc** [comment]
fix issue https://github.com/ingadhoc/odoo-argentina-ce/issues/57

**Comment by filoquin** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin. I'm afraid I can't do that.

**Pull request merged**
