### PR TITLE
[MIG] l10n_ar_afipws: Migration to 17.0

### PR DESCRIPTION
**Pull request by maq-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/odoo-argentina-ce/pull/56).

**Comment by filoquin** [comment]
@roboadhoc r+ override=ci/runbot-odoo-argentina-ce

**Comment by roboadhoc** [comment]
I'm sorry, @filoquin:
- you can't review+.
- you are not allowed to override this status.

**Comment by maq-adhoc** [comment]
@roboadhoc r+ override=ci/runbot-odoo-argentina-ce

**Comment by maq-adhoc** [comment]
@roboadhoc r+  squash

**Comment by roboadhoc** [comment]
Merge method set to squash.

**Comment by maq-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc: this PR is already reviewed, reviewing it again is useless.

**Pull request merged**
