### PR TITLE
[WIP] Reorder CAEA

### PR DESCRIPTION
**Pull request by filoquin**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/odoo-argentina-ce/pull/41).

**Comment by maq-adhoc** [comment]
@roboadhoc rebase-ff r+

**Comment by roboadhoc** [comment]
I'm sorry, @maq-adhoc. I'm afraid I can't do that.

**Comment by jjscarafia** [comment]
@roboadhoc r+ rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Pull request closed without merging**
